= Maintainer Guide
:toclevels: 6
:toc:

== Audience
You are involved in maintaining/releasing test-doc-blocks.

== Releasing
A release is triggered manually via a GitHub Action "Release" workflow.

=== Automated Workflow
Our https://github.com/lread/test-doc-blocks/actions?query=workflow%3A%22Release%22[Release] GitHub Action handles the release workflow.

Our GitHub Actions "Release" workflow:

. Create a thin jar using our version scheme
. Apply jar version to the following docs:
.. user guide docs `deps.edn` usage example
.. change log "unreleased" and "unreleased breaking changes" headings
. Deploy the jar to clojars
. Commit and push updates made to `CHANGELOG.adoc` and `01-user-guide.adoc` back to the project
. Create and push a release tag back to the project repo
. Inform cljdoc of the new release

At this time, the release workflow does not run tests.
The assumption is that you've waited for the last CI test run to complete and are happy with the results.

The release workflow will fail if the change log is not ready for release.

=== Updating the Version

Edit `version.edn` in the project root.
The release workflow consults this file when constructing the version.

=== Special Setup

GitHub has been configured with necessary secrets for GitHub Actions to deploy test-doc-blocks to clojars.

=== Local Verification
To run the change log validation locally:

[source,shell]
----
bb ci-release validate
----

If you so wish, you can also locally run all steps up to, but not including, deploy via:

[source,shell]
----
bb ci-release prep
----
Locally verify, but do NOT check in changes `prep` makes to `CHANGELOG.adoc`, `pom.xml` and `doc/01-user-guide.adoc`.

=== Invoking a Release
As a maintainer, you should have sufficient privileges to see a "Run Workflow" dropdown button on the https://github.com/lread/test-doc-blocks/actions/workflows/release.yml?query=workflow%3ARelease[Release] action page.
The dropdown will prompt for a branch.
I did not see a way to disable this prompt, leave it at "main" and run the workflow.

TIP: Remember to pull after a release to get the changes made by the release workflow.
